[package]
name = "packed_struct_codegen"
description = "This crate implements the code generation for the packed_struct library."
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
quote.workspace = true
syn.workspace = true
proc-macro2.workspace = true

[lib]
proc-macro = true

[features]
default = []
std = []
alloc = []
