[package]
name = "packed_struct"
description = "Binary-level structure packing and unpacking generator"
homepage = "http://www.hashmismatch.net/libraries/packed-struct/"
keywords = ["enum", "packing", "serialization"]
categories = ["encoding"]
readme = "../README.md"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
packed_struct_codegen.workspace = true
serde = { workspace = true, optional = true }
bitvec.workspace = true

[features]
default = ["std"]
std = ["serde?/std", "packed_struct_codegen/std"]
alloc = ["packed_struct_codegen/alloc"]
byte_types_64 = []
byte_types_256 = []
use_serde = ["dep:serde", "serde/derive"]
